version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
  - dependency-name: prometheus-client
    versions:
    - 0.10.0
    - 0.10.1
    - 0.9.0
  - dependency-name: grpcio
    versions:
    - 1.37.0
  - dependency-name: protobuf
    versions:
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: pytest
    versions:
    - 6.2.2
    - 6.2.3
  - dependency-name: fire
    versions:
    - 0.4.0
  - dependency-name: isort
    versions:
    - 5.7.0
    - 5.8.0
  - dependency-name: httpx
    versions:
    - 0.17.1
  - dependency-name: peewee
    versions:
    - 3.14.1
    - 3.14.2
    - 3.14.3
    - 3.14.4
  - dependency-name: sentry-sdk
    versions:
    - 0.19.5
    - 0.20.0
    - 0.20.1
    - 0.20.2
    - 0.20.3
    - 1.0.0
  - dependency-name: aiohttp
    versions:
    - 3.7.3
    - 3.7.4
  - dependency-name: cryptography
    versions:
    - 3.3.2
    - 3.4.1
    - 3.4.3
    - 3.4.7
  - dependency-name: grpcio-tools
    versions:
    - 1.35.0
