{
 "title": "Shadowsocks监控",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ss_node",
    "label": "ss_node",
    "query": "label_values(ss_node_info,ss_node_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "内存使用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"ss\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU使用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"ss\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "流量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "流量速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(network_transmit_bytes_total{job=\"ss\",ss_node=~\"$ss_node\"}[2m])",
     "legendFormat": "{{ss_node}}"
    }
   ]
  },
  {
   "title": "总流量",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "network_transmit_bytes_total{job=\"ss\"}",
     "legendFormat": "{{ss_node}}"
    }
   ]
  },
  { "title": "连接数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "当前活跃接数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "active_connection_count{job=\"ss\",ss_node=~\"$ss_node\"}",
     "legendFormat": "{{ss_node}}"
    }
   ]
  },
  {
   "title": "处理的总链接数",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "connection_made_count_total{job=\"ss\"}",
     "legendFormat": "{{ss_node}}"
    }
   ]
  },
  { "title": "加/解密", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "用户握手时间",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s", "label": "时间" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,rate(find_access_user_time_seconds_bucket{job=~\"ss\",ss_node=~\"$ss_node\"}[2m]))",
     "legendFormat": "{{ss_node}}"
    }
   ]
  },
  {
   "title": "加/解密响应时间",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s", "label": "时间" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.8,rate(decrypt_data_time_seconds_bucket{job=\"ss\",ss_node=~\"$ss_node\"}[2m]))",
     "legendFormat": "{{ss_node}}-加密"
    },
    {
     "expr": "histogram_quantile(0.8,rate(encrypt_data_time_seconds_bucket{job=\"ss\",ss_node=~\"$ss_node\"}[2m]))",
     "legendFormat": "{{ss_node}}-解密"
    }
   ]
  },
  {
   "title": "加/解密请求频率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "时间" }
   ],
   "targets": [
    {
     "expr": "rate(encrypt_data_time_seconds_count{job=\"ss\",ss_node=~\"$ss_node\"}[2m])",
     "legendFormat": "加密 - {{ss_node}}"
    },
    {
     "expr": "rate(decrypt_data_time_seconds_count{job=\"ss\",ss_node=~\"$ss_node\"}[2m])",
     "legendFormat": "解密 - {{ss_node}}"
    }
   ]
  }
 ]
}