# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shadowsocks/protos/aioshadowsocks.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="shadowsocks/protos/aioshadowsocks.proto",
    package="aioshadowsocks",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\'shadowsocks/protos/aioshadowsocks.proto\x12\x0e\x61ioshadowsocks"\x1c\n\tUserIdReq\x12\x0f\n\x07user_id\x18\x01 \x01(\x05"Z\n\x07UserReq\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x0e\n\x06\x65nable\x18\x05 \x01(\x08"\x07\n\x05\x45mpty"W\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x0e\n\x06\x65nable\x18\x05 \x01(\x08"t\n\nUserServer\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x16\n\x0eupload_traffic\x18\x02 \x01(\x03\x12\x18\n\x10\x64ownload_traffic\x18\x03 \x01(\x03\x12\x0f\n\x07ip_list\x18\x04 \x03(\t\x12\x12\n\nis_running\x18\x05 \x01(\x08\x32\xdd\x03\n\x02ss\x12=\n\nCreateUser\x12\x17.aioshadowsocks.UserReq\x1a\x14.aioshadowsocks.User"\x00\x12=\n\nUpdateUser\x12\x17.aioshadowsocks.UserReq\x1a\x14.aioshadowsocks.User"\x00\x12<\n\x07GetUser\x12\x19.aioshadowsocks.UserIdReq\x1a\x14.aioshadowsocks.User"\x00\x12@\n\nDeleteUser\x12\x19.aioshadowsocks.UserIdReq\x1a\x15.aioshadowsocks.Empty"\x00\x12I\n\x0eInitUserServer\x12\x19.aioshadowsocks.UserIdReq\x1a\x1a.aioshadowsocks.UserServer"\x00\x12H\n\rGetUserServer\x12\x19.aioshadowsocks.UserIdReq\x1a\x1a.aioshadowsocks.UserServer"\x00\x12\x44\n\x0eStopUserServer\x12\x19.aioshadowsocks.UserIdReq\x1a\x15.aioshadowsocks.Empty"\x00\x62\x06proto3'
    ),
)


_USERIDREQ = _descriptor.Descriptor(
    name="UserIdReq",
    full_name="aioshadowsocks.UserIdReq",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="user_id",
            full_name="aioshadowsocks.UserIdReq.user_id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=59,
    serialized_end=87,
)


_USERREQ = _descriptor.Descriptor(
    name="UserReq",
    full_name="aioshadowsocks.UserReq",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="user_id",
            full_name="aioshadowsocks.UserReq.user_id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="port",
            full_name="aioshadowsocks.UserReq.port",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="method",
            full_name="aioshadowsocks.UserReq.method",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="password",
            full_name="aioshadowsocks.UserReq.password",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="enable",
            full_name="aioshadowsocks.UserReq.enable",
            index=4,
            number=5,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=89,
    serialized_end=179,
)


_EMPTY = _descriptor.Descriptor(
    name="Empty",
    full_name="aioshadowsocks.Empty",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=181,
    serialized_end=188,
)


_USER = _descriptor.Descriptor(
    name="User",
    full_name="aioshadowsocks.User",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="user_id",
            full_name="aioshadowsocks.User.user_id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="port",
            full_name="aioshadowsocks.User.port",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="method",
            full_name="aioshadowsocks.User.method",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="password",
            full_name="aioshadowsocks.User.password",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="enable",
            full_name="aioshadowsocks.User.enable",
            index=4,
            number=5,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=190,
    serialized_end=277,
)


_USERSERVER = _descriptor.Descriptor(
    name="UserServer",
    full_name="aioshadowsocks.UserServer",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="user_id",
            full_name="aioshadowsocks.UserServer.user_id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="upload_traffic",
            full_name="aioshadowsocks.UserServer.upload_traffic",
            index=1,
            number=2,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="download_traffic",
            full_name="aioshadowsocks.UserServer.download_traffic",
            index=2,
            number=3,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="ip_list",
            full_name="aioshadowsocks.UserServer.ip_list",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="is_running",
            full_name="aioshadowsocks.UserServer.is_running",
            index=4,
            number=5,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=279,
    serialized_end=395,
)

DESCRIPTOR.message_types_by_name["UserIdReq"] = _USERIDREQ
DESCRIPTOR.message_types_by_name["UserReq"] = _USERREQ
DESCRIPTOR.message_types_by_name["Empty"] = _EMPTY
DESCRIPTOR.message_types_by_name["User"] = _USER
DESCRIPTOR.message_types_by_name["UserServer"] = _USERSERVER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserIdReq = _reflection.GeneratedProtocolMessageType(
    "UserIdReq",
    (_message.Message,),
    dict(
        DESCRIPTOR=_USERIDREQ,
        __module__="shadowsocks.protos.aioshadowsocks_pb2"
        # @@protoc_insertion_point(class_scope:aioshadowsocks.UserIdReq)
    ),
)
_sym_db.RegisterMessage(UserIdReq)

UserReq = _reflection.GeneratedProtocolMessageType(
    "UserReq",
    (_message.Message,),
    dict(
        DESCRIPTOR=_USERREQ,
        __module__="shadowsocks.protos.aioshadowsocks_pb2"
        # @@protoc_insertion_point(class_scope:aioshadowsocks.UserReq)
    ),
)
_sym_db.RegisterMessage(UserReq)

Empty = _reflection.GeneratedProtocolMessageType(
    "Empty",
    (_message.Message,),
    dict(
        DESCRIPTOR=_EMPTY,
        __module__="shadowsocks.protos.aioshadowsocks_pb2"
        # @@protoc_insertion_point(class_scope:aioshadowsocks.Empty)
    ),
)
_sym_db.RegisterMessage(Empty)

User = _reflection.GeneratedProtocolMessageType(
    "User",
    (_message.Message,),
    dict(
        DESCRIPTOR=_USER,
        __module__="shadowsocks.protos.aioshadowsocks_pb2"
        # @@protoc_insertion_point(class_scope:aioshadowsocks.User)
    ),
)
_sym_db.RegisterMessage(User)

UserServer = _reflection.GeneratedProtocolMessageType(
    "UserServer",
    (_message.Message,),
    dict(
        DESCRIPTOR=_USERSERVER,
        __module__="shadowsocks.protos.aioshadowsocks_pb2"
        # @@protoc_insertion_point(class_scope:aioshadowsocks.UserServer)
    ),
)
_sym_db.RegisterMessage(UserServer)


_SS = _descriptor.ServiceDescriptor(
    name="ss",
    full_name="aioshadowsocks.ss",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=398,
    serialized_end=875,
    methods=[
        _descriptor.MethodDescriptor(
            name="CreateUser",
            full_name="aioshadowsocks.ss.CreateUser",
            index=0,
            containing_service=None,
            input_type=_USERREQ,
            output_type=_USER,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="UpdateUser",
            full_name="aioshadowsocks.ss.UpdateUser",
            index=1,
            containing_service=None,
            input_type=_USERREQ,
            output_type=_USER,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="GetUser",
            full_name="aioshadowsocks.ss.GetUser",
            index=2,
            containing_service=None,
            input_type=_USERIDREQ,
            output_type=_USER,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="DeleteUser",
            full_name="aioshadowsocks.ss.DeleteUser",
            index=3,
            containing_service=None,
            input_type=_USERIDREQ,
            output_type=_EMPTY,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="InitUserServer",
            full_name="aioshadowsocks.ss.InitUserServer",
            index=4,
            containing_service=None,
            input_type=_USERIDREQ,
            output_type=_USERSERVER,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="GetUserServer",
            full_name="aioshadowsocks.ss.GetUserServer",
            index=5,
            containing_service=None,
            input_type=_USERIDREQ,
            output_type=_USERSERVER,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="StopUserServer",
            full_name="aioshadowsocks.ss.StopUserServer",
            index=6,
            containing_service=None,
            input_type=_USERIDREQ,
            output_type=_EMPTY,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_SS)

DESCRIPTOR.services_by_name["ss"] = _SS

# @@protoc_insertion_point(module_scope)
