# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: shadowsocks/protos/aioshadowsocks.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import shadowsocks.protos.aioshadowsocks_pb2


class ssBase(abc.ABC):
    @abc.abstractmethod
    async def CreateUser(self, stream):
        pass

    @abc.abstractmethod
    async def UpdateUser(self, stream):
        pass

    @abc.abstractmethod
    async def GetUser(self, stream):
        pass

    @abc.abstractmethod
    async def DeleteUser(self, stream):
        pass

    @abc.abstractmethod
    async def InitUserServer(self, stream):
        pass

    @abc.abstractmethod
    async def GetUserServer(self, stream):
        pass

    @abc.abstractmethod
    async def StopUserServer(self, stream):
        pass

    def __mapping__(self):
        return {
            "/aioshadowsocks.ss/CreateUser": grpclib.const.Handler(
                self.CreateUser,
                grpclib.const.Cardinality.UNARY_UNARY,
                shadowsocks.protos.aioshadowsocks_pb2.UserReq,
                shadowsocks.protos.aioshadowsocks_pb2.User,
            ),
            "/aioshadowsocks.ss/UpdateUser": grpclib.const.Handler(
                self.UpdateUser,
                grpclib.const.Cardinality.UNARY_UNARY,
                shadowsocks.protos.aioshadowsocks_pb2.UserReq,
                shadowsocks.protos.aioshadowsocks_pb2.User,
            ),
            "/aioshadowsocks.ss/GetUser": grpclib.const.Handler(
                self.GetUser,
                grpclib.const.Cardinality.UNARY_UNARY,
                shadowsocks.protos.aioshadowsocks_pb2.UserIdReq,
                shadowsocks.protos.aioshadowsocks_pb2.User,
            ),
            "/aioshadowsocks.ss/DeleteUser": grpclib.const.Handler(
                self.DeleteUser,
                grpclib.const.Cardinality.UNARY_UNARY,
                shadowsocks.protos.aioshadowsocks_pb2.UserIdReq,
                shadowsocks.protos.aioshadowsocks_pb2.Empty,
            ),
            "/aioshadowsocks.ss/InitUserServer": grpclib.const.Handler(
                self.InitUserServer,
                grpclib.const.Cardinality.UNARY_UNARY,
                shadowsocks.protos.aioshadowsocks_pb2.UserIdReq,
                shadowsocks.protos.aioshadowsocks_pb2.UserServer,
            ),
            "/aioshadowsocks.ss/GetUserServer": grpclib.const.Handler(
                self.GetUserServer,
                grpclib.const.Cardinality.UNARY_UNARY,
                shadowsocks.protos.aioshadowsocks_pb2.UserIdReq,
                shadowsocks.protos.aioshadowsocks_pb2.UserServer,
            ),
            "/aioshadowsocks.ss/StopUserServer": grpclib.const.Handler(
                self.StopUserServer,
                grpclib.const.Cardinality.UNARY_UNARY,
                shadowsocks.protos.aioshadowsocks_pb2.UserIdReq,
                shadowsocks.protos.aioshadowsocks_pb2.Empty,
            ),
        }


class ssStub:
    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.CreateUser = grpclib.client.UnaryUnaryMethod(
            channel,
            "/aioshadowsocks.ss/CreateUser",
            shadowsocks.protos.aioshadowsocks_pb2.UserReq,
            shadowsocks.protos.aioshadowsocks_pb2.User,
        )
        self.UpdateUser = grpclib.client.UnaryUnaryMethod(
            channel,
            "/aioshadowsocks.ss/UpdateUser",
            shadowsocks.protos.aioshadowsocks_pb2.UserReq,
            shadowsocks.protos.aioshadowsocks_pb2.User,
        )
        self.GetUser = grpclib.client.UnaryUnaryMethod(
            channel,
            "/aioshadowsocks.ss/GetUser",
            shadowsocks.protos.aioshadowsocks_pb2.UserIdReq,
            shadowsocks.protos.aioshadowsocks_pb2.User,
        )
        self.DeleteUser = grpclib.client.UnaryUnaryMethod(
            channel,
            "/aioshadowsocks.ss/DeleteUser",
            shadowsocks.protos.aioshadowsocks_pb2.UserIdReq,
            shadowsocks.protos.aioshadowsocks_pb2.Empty,
        )
        self.InitUserServer = grpclib.client.UnaryUnaryMethod(
            channel,
            "/aioshadowsocks.ss/InitUserServer",
            shadowsocks.protos.aioshadowsocks_pb2.UserIdReq,
            shadowsocks.protos.aioshadowsocks_pb2.UserServer,
        )
        self.GetUserServer = grpclib.client.UnaryUnaryMethod(
            channel,
            "/aioshadowsocks.ss/GetUserServer",
            shadowsocks.protos.aioshadowsocks_pb2.UserIdReq,
            shadowsocks.protos.aioshadowsocks_pb2.UserServer,
        )
        self.StopUserServer = grpclib.client.UnaryUnaryMethod(
            channel,
            "/aioshadowsocks.ss/StopUserServer",
            shadowsocks.protos.aioshadowsocks_pb2.UserIdReq,
            shadowsocks.protos.aioshadowsocks_pb2.Empty,
        )
